#!/bin/bash

# SCRIPT_DIR="${BUILD_DIR%/Build/*}/SourcePackages/checkouts/MKUtils/Resources/LocalizeKit"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# swift run generate <p> <t>
# <-p> 패키지 파일의 Root 폴더 위치를 설정하세요
# <-t> 스크립트가 동작할 패키지 목록을 배열형태로 설정하세요 (eg. PhotoScene NoteScene)

cd "$SCRIPT_DIR"
xcrun -sdk macosx swift run Localizing generate \
-p "${SCRIPT_DIR}/Sources" \
-t "Example"

#-p "${SRCROOT}/Packages" \
-t ""

#rm -rf "$SCRIPT_DIR/.build"
