// swiftlint:disable all

// Do not Edit this file manually
// Auto Genrated by Localizing Script `generate`
// This file generated by `Script..`exec


import Foundation

struct I18N {
    static let test = "test".localized
    static let test2 = "test2".localized
}

extension String {
    var localized: String {
        return NSLocalizedString(self, comment: "")
    }
}
