// swiftlint:disable all
//
//  LocalizingGenerator.swift
//

import Foundation

public class LocalizingGenerator {

    public let binaryFolderURL: URL
    
    var scriptPath: String {
        return self.binaryFolderURL.path + "/run"
    }
    
    public init(binaryFolderURL: URL) {
        self.binaryFolderURL = binaryFolderURL
    }
    
    @discardableResult
    /// folder: ko.lproj Dir path
    public func runI18N(from folder: URL) throws -> String {
        // Add the binary folder URL to $PATH so the script can find pre-compiled `node`
        
        let command = "export PATH=$PATH:'\(self.binaryFolderURL.path)'"
        // Log out the version for debugging purposes
//         + " && '\(self.scriptPath)' --version"
        
        // Set the final command to log out the passed-in arguments for debugging purposes
//        + " && set -x"
        
        // Actually run the script with the given options.
//        + " && '\(self.scriptPath)' \(arguments.joined(separator: " "))"
        
        + """
        "touch I18N.swift"
        echo "// swiftlint:disable all" >> I18N.swift
        echo "" >> I18N.swift
        echo "// Do not Edit this file manually" >> I18N.swift
        echo "// Auto Genrated by Localizing Script \\`generate\\`" >> I18N.swift
        echo "// This file generated by \\`Script..\\`exec" >> I18N.swift
        echo "" >> I18N.swift
        echo "import Foundation" >> I18N.swift
        echo "import LocalizeGen" >> I18N.swift
        echo "" >> I18N.swift
        echo "struct I18N {" >> I18N.swift
        
        file="\(folder.path)/Localizable.strings" # 위치를 개발하시는 프로젝트의 파일 위치로 고쳐주세요.
        while IFS= read -r line
        do
            variableName=$(echo ${line%%=*})
        if
            [ "$variableName" != "" ]
        then
            echo "    static let $variableName = \\"$variableName\\".localized(bundle: .module)" >> I18N.swift
        fi

        done <"$file"
        echo "}" >> I18N.swift
        echo "" >> I18N.swift

        """
        return try Basher.run(command: command, from: folder)
    }
}
