// swiftlint:disable all

// Do not Edit this file manually
// Auto Genrated by Localizing Script `generate`
// This file generated by `Script..`exec

import Foundation
import LocalizeGen

struct I18N {
    static let test = "test".localized(bundle: .module)
    static let test2 = "test2".localized(bundle: .module)
}

