#!/bin/bash

targetfile="${BUILD_DIR%/Build/*}/SourcePackages/checkouts/MKUtils/Resources/SwiftLint/swiftlint.yml"
export PATH="$PATH:/opt/homebrew/bin"

if which swiftlint > /dev/null; then
 swiftlint --config $targetfile
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi

