#!/usr/bin/env sh

XCODE_USER_TEMPLATES_DIR="$HOME/Library/Developer/Xcode/Templates/File Templates"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TEMPLATES_DIR="Clean Swift"


xcodeTemplate () {
	echo "==> Clean up Clean Swift Xcode file templates..."

	rm -fR "$XCODE_USER_TEMPLATES_DIR/$TEMPLATES_DIR"
	echo "==> remove Legacy Template"
}

xcodeTemplate

echo "==> ... success!"